version: "3"
services:
    personal-information_svc:
        container_name: personal-information_docker
        build:
            context: personal-information

        image: personal-information_docker:latest
        networks:
            - network
        ports:
            - "8080:8080"
#        depends_on:
        links:
            - db_pi



#create DB for all services: academic-performance (ap), period-planning(pp), schedule-calendar(sc), personal-information(pi)

    db_pi:
        image: "postgres" # use latest official postgres version
        container_name: db_pi
        env_file:
           - database.env # configure postgres
#        ports:
#           - "5432:5432"
#        ports:
#           - ${POSTGRES_PORT_PI:-5435}:5432
#        volumes:
#          - ./pg_db/database_data:/var/lib/postgresql/data
#          - ./pg_db/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - network





networks:
  # Declare our private network.  We must declare one for the magic
  # Docker DNS to work, but otherwise its default settings are fine.
  network: {}
